### ISSUE TITLE
Epic qui concerne mon cv (cv.stephane-klein.info)

### ISSUE THREAD

**Issue by stephane-klein** [stephane-klein/backlog#174]
Todo :

- [x] Créer un compte sur https://rxresu.me/klein/stphane-klein (CV pas encore publié)
- [ ] #123 - Recréer le contenu de https://cv.stephane-klein.info sans y apporter aucun changement de contenu, ni porter attention sur le thème
  - [ ] Version FR
  - [ ] Version EN 
- [ ] Si le test est concluant 
  - [ ] Sauvegarder l'export jsonresume dans le repos https://github.com/stephane-klein/sklein.xyz
  - [ ] enable le CV sur https://rxresu.me/klein/stphane-klein
  - [ ] Mettre en place une redirection non permanente de https://cv.stephane-klein.info vers le CV https://rxresu.me/klein/stphane-klein
  - [ ] Essayer de mettre à jour le contenu (peut-être que cette partie fera l'objet d'une autre issue, donc issue à extraire)
    - [ ] Ajouter l'XP Spacefill
      - [ ] Rédiger une version plus minimaliste
    - [ ] Mettre à jour la partie technologie
    - [ ] ...
   - [ ] Essayer de self hosted en SSG le CV (pas la partie éditeur) pour l'héberger directement sur cv.stephane-klein.info
     - [ ] Si pas possible ou trop long, configurer un [reverse proxy](https://en.wikipedia.org/wiki/Reverse_proxy) sur cv.stephane-klein.info
   - [ ] Est-ce que je dois déplacer cv.stephane-klein.info vers cv.sklein.xyz ?
